spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/notifyhub
    username: notifyhub
    password: notifyhub
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
server:
  port: 8081
notifyhub:
  worker:
    poll-delay-ms: 5000
logging:
  level:
    com.notifyhub.worker.service.InboundMessageProcessor: DEBUG
